# Regenerate the count matrix in docs/02_cards.md, and check coverage both ways.
#
# The matrix was maintained by hand across six decklists. At eight it is a table
# nobody can keep right by eye, and a wrong cell in it is the worst kind of
# error this project makes: a **confidently wrong diagnostic**, which reads as a
# fact about the decks and misdirects a decision.
#
# TWO CHECKS, BOTH DIRECTIONS. Every row of the card database must have a file
# in docs/cards/, and every file must have a row. One direction alone passes
# while the other silently rots: a card added to the database with no file is
# undocumented, and a file with no row is a card the simulator cannot see.
#
# The block rewritten is everything between the "## Counts across" heading and
# the next "## " heading. Nothing else in the file is touched, because the rest
# is prose nobody should generate.
#
# Run with:
#   "/c/Program Files/R/R-4.6.1/bin/Rscript.exe" \
#     scripts/refresh_card_index_claude.R

rm(list = ls())

for(one_file in list.files("R", pattern = "[.]R$", full.names = TRUE)){
  source(one_file)
}

index_path <- file.path("docs", "02_cards.md")
card_df <- build_card_database()

# ---------------------------------------------------------------------------
# Coverage, both ways
# ---------------------------------------------------------------------------

file_vec <- list.files(file.path("docs", "cards"), pattern = "[.]md$")
file_id_vec <- sub("^([A-Z]+)-([0-9]+)-.*$", "\\1-\\2", file_vec)

missing_file_vec <- setdiff(card_df$card_id, file_id_vec)
if(length(missing_file_vec) > 0){
  stop("card database rows with no docs/cards/ file: ",
       paste0(missing_file_vec, collapse = ", "))
}
missing_row_vec <- setdiff(file_id_vec, card_df$card_id)
if(length(missing_row_vec) > 0){
  stop("docs/cards/ files with no card database row: ",
       paste0(missing_row_vec, collapse = ", "))
}
print(paste0("coverage: ", length(file_vec), " files, ", nrow(card_df),
             " database rows, both directions clean"))

# ---------------------------------------------------------------------------
# The matrix
# ---------------------------------------------------------------------------

path_vec <- sort(list.files("decklists", pattern = "[.]txt$",
                            full.names = TRUE))
name_vec <- sub("[.]txt$", "", basename(path_vec))
count_list <- lapply(path_vec, function(one_path){
  read_decklist(one_path, card_df)$count_vec
})
names(count_list) <- name_vec

#' How many copies of one card a decklist runs
#'
#' Reads the CANONICAL id, since `read_decklist()` has already folded alternate
#' printings together -- so a decklist citing Buddy-Buddy Poffin MEG 167 counts
#' under TEF 144 and the matrix must ask for it there.
#' @noRd
.count_of <- function(count_vec, card_id){
  card_id <- canonical_card_id(card_id)
  if(card_id %in% names(count_vec)) as.integer(count_vec[[card_id]]) else 0L
}

#' The docs/cards/ link for one card id, or the bare id if the file is missing
#' @noRd
.file_link <- function(card_id){
  hit_vec <- file_vec[file_id_vec == card_id]
  if(length(hit_vec) == 0) return(card_id)

  set_str <- sub("-.*$", "", card_id)
  num_str <- as.integer(sub("^[A-Z]+-", "", card_id))
  paste0("[", set_str, " ", num_str, "](cards/", hit_vec[1], ")")
}

# Rows are the cards that appear in at least one list, ordered as the database
# orders them -- which groups the Bronzong line first and the Energy last, and
# is the order a reader of docs/cards/ already has in their head.
appear_vec <- card_df$card_id[sapply(card_df$card_id, function(one_id){
  any(sapply(count_list, .count_of, card_id = one_id) > 0)
})]
# An alias contributes its counts to the canonical row, so listing it again as
# its own row would double-count it in the reader's eye.
appear_vec <- unique(canonical_card_id(appear_vec))

header_vec <- sub("^decklist", "", name_vec)
line_vec <- c(
  paste0("## Counts across the ", length(name_vec), " decklists"),
  "",
  paste0("Regenerated by `scripts/refresh_card_index_claude.R`; do not edit by ",
         "hand. `.` = not in that list, and a **bold** card name is one whose ",
         "count varies across the lists."),
  "",
  paste0("| Card | File | ", paste0(header_vec, collapse = " | "), " |"),
  paste0("|------|------|", paste0(rep("---", length(name_vec)),
                                    collapse = "|"), "|"))

for(one_id in appear_vec){
  count_row <- sapply(count_list, .count_of, card_id = one_id)
  name_str <- lookup_card(card_df, one_id)$name
  # Two Bronzor printings share a name, so the set code has to disambiguate.
  if(sum(card_df$name == name_str) > 1){
    name_str <- paste0(name_str, " (", sub("-.*$", "", one_id), ")")
  }
  if(length(unique(count_row)) > 1) name_str <- paste0("**", name_str, "**")

  cell_vec <- ifelse(count_row == 0, ".", as.character(count_row))
  line_vec <- c(line_vec,
                paste0("| ", name_str, " | ", .file_link(one_id), " | ",
                       paste0(cell_vec, collapse = " | "), " |"))
}
line_vec <- c(line_vec, "")

# ---------------------------------------------------------------------------
# Splice it in
# ---------------------------------------------------------------------------

old_vec <- readLines(index_path)
start_idx <- grep("^## Counts across", old_vec)
if(length(start_idx) != 1) stop("expected exactly one '## Counts across' heading")
after_idx <- grep("^## ", old_vec)
after_idx <- after_idx[after_idx > start_idx]
if(length(after_idx) == 0) stop("no heading follows the counts block")

new_vec <- c(old_vec[seq_len(start_idx - 1L)], line_vec,
             old_vec[after_idx[1]:length(old_vec)])
writeLines(new_vec, index_path)
print(paste0("wrote ", index_path, ": ", length(appear_vec), " cards x ",
             length(name_vec), " decklists"))
